name: all_flutter_testing
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  math_expressions: ^2.4.0
  shared_preferences: ^2.0.17
  flutter_native_splash: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

flutter_native_splash:
  android: true
  web: false
  ios: false
  color: "#000000"
  image: "assets/img/calc.png"
